### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by zachlatta** [H-M-H/Weylus#3]
Does this project support Wayland? I'm running the latest on https://aur.archlinux.org/packages/weylus-bin/ and while I have input working, I'm getting a black screen on the iPad browser I'm using it from.

Input also seems to be smooth in Xwayland apps, but jumpy in Wayland native apps.

**Comment by H-M-H** [comment]
Right now screen casting is not supported for Wayland. Currently the screen is captured either via [autopilot](https://github.com/autopilot-rs/autopilot-rs), which only supports X11, or using `XShmCreateImage` here: https://github.com/H-M-H/Weylus/blob/435373be5141a2b03aeab6549225a5a5790ed1b7/lib/linux/capture.c .

To get Wayland to work there are some things I still need to find out:
- check if we a running Wayland or X (this is probably easy)
- find an API to capture the screen and selected windows, that is fast enough
  - preferably similar to the X11 API that allows me to get a pointer to the RGB buffer of some window
- API to request which windows should show up in the window selection menu

If someone wants to help me here a minimal working example of taking a screenshot of a selected window in Wayland would be great, provided it is written in Rust, C or C++. Alternatively point me to a tool that already does that.
I will probably write some Trait to abstract different window systems, so I would rather not want a pull request now.

**Comment by H-M-H** [comment]
About the input issues: I am not sure what's causing that, I do not do anything specific to X11.
Can you tell me if `libinput debug-events` or `evtest` outputs anything strange?

Also this should probably be a separate issue.

**Comment by H-M-H** [comment]
Looks like the tool you used (https://github.com/ammen99/wf-recorder) for recording and https://github.com/emersion/grim can be used as a reference.

**Comment by zachlatta** [comment]
Hey @H-M-H, thank you for your willingness to work on Wayland support and I'm sorry I can't do more to help right now. Realistically, I don't think I'm going to be able to help you debug libinput or evtest right now. I love this project and think it's absolutely amazing. Wish I had more time to help out.

**Comment by H-M-H** [comment]
I did some research and the situation regarding capturing the screen or even windows on wayland is pretty dire. There is no equivalent to X11's `XShmGetImage` or `XGetImage`, Wayland itself just does not support capturing the screen. Instead it is the responsibility of the compositor to expose an API to take screenshots. But unfortunately this is not [standardized](https://xkcd.com/927/), there is:
- wlroots' [wlr-screencopy-unstable-v1](https://github.com/swaywm/wlroots/blob/master/protocol/wlr-screencopy-unstable-v1.xml) which does not work for gnome or kde
- there is Wayland's reference compositor Weston with another [way](https://github.com/wayland-project/weston/blob/master/clients/screenshot.c)
- there is gnome's [screenshot](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/86b5a43008aa5afad6bfefe5542f048de226e575/data/dbus-interfaces/org.gnome.Shell.Screenshot.xml) and [screen cast](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/86b5a43008aa5afad6bfefe5542f048de226e575/data/dbus-interfaces/org.gnome.Shell.Screencast.xml) interface via dbus, both probably too slow for proper streaming
- there is kde's dbus interface for [screenshots](https://github.com/KDE/kwin/tree/617650d4405774358118866062ece477401652f2/effects/screenshot)

**Comment by pointhi** [comment]
What about [PipeWire](https://pipewire.org/)?

> Capture and playback of audio and video with minimal latency.

**Comment by H-M-H** [comment]
Interesting, I did not know about PipeWire, the [docs](https://gitlab.freedesktop.org/pipewire/pipewire/-/tree/master/doc) are a bit lacking but PipeWire is used by [webrtc](https://webrtc.googlesource.com/src/+/refs/heads/master/modules/desktop_capture/linux/base_capturer_pipewire.cc), so a look at how they do it might help. @pointhi do you know what latency one can expect using PipeWire? For reference: capturing a 1920x1080 raw bgr0 frame on my system takes about 0.8 milliseconds if the screen contents do not change too much.

**Comment by pointhi** [comment]
I never used PipeWire, but it was designed for remote desktop applications on Wayland to my knowledge.

**Comment by ilya-epifanov** [comment]
strangely enough, unfocused windows do get captured, until the very first event sent to them which focuses them and then the output becomes black

**Comment by H-M-H** [comment]
I think I have a good idea of what's going on: If a window is not focused, Weylus captures it directly by its window handle but if it is active Weylus captures the part of the root window containing the window to be captured. The reason for this is to have things like context menus that are their own windows in themselves still show up. But I guess XWayland doesn't like capturing the root window and just decides to have it black.

**Comment by H-M-H** [comment]
Please check if things work better with the latest build: https://github.com/H-M-H/Weylus/actions/runs/585393503#artifacts

**Comment by H-M-H** [comment]
I started experimenting with pipewire as this seems to be the most promising solution here: https://github.com/H-M-H/Weylus/tree/wayland

For now only requesting a screen cast via [org.freedesktop.portal.ScreenCast](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.ScreenCast) is implemented. That means there now is a file descriptor that can be used to connect to pipewire. Unfortunately the docs on how to use pipewire directly are still very lacking. For example [pw_remote_connect_fd](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-ScreenCast.OpenPipeWireRemote) mentioned in the docs for org.freedesktop.portal.ScreenCast has been removed in pipewire 0.3 and seems to be pw_context_connect_fd now. All I could find on video processing is: https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/doc/tutorial5.md

It looks like pipewire implements a [gstreamer plugin](https://gitlab.freedesktop.org/pipewire/pipewire/-/tree/master/src/gst), I suspect gstreamer's API is not as badly documented, so this is perhaps worth a look.

A problem that remains is that it looks like there is no way to get the position of a captured window, which means Weylus won't be able to properly map the input to the window. As it stands only capturing the full desktop will be usable under Wayland.

**Comment by H-M-H** [comment]
For anyone interested, https://github.com/H-M-H/Weylus/commit/d632a7dfdfacd27aaa0576076f9e2d3b0b32d93c implements screen casting via gstreamer. Binaries can be found [here](https://github.com/H-M-H/Weylus/actions/runs/691851871#artifacts). There still are quite some issues, refer to the commit message for details.

**Comment by H-M-H** [comment]
Looks like once [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/120) is resolved, working with cursor metadata via gstreamer will make dynamically showing and hiding the cursor possible.

Regarding window titles I opened a feature request here: https://github.com/flatpak/xdg-desktop-portal/issues/569

**Comment by dmoltisanti** [comment]
Thanks a lot for working on this :)

**Comment by H-M-H** [comment]
Thanks! So far walking this path has been rather rocky and I have hit quite some bugs on the way:
### Bugs
- [kwin_wayland dies](https://bugs.kde.org/show_bug.cgi?id=435042#add_comment) and tears down the entire plasma desktop
- PipeWire deadlock [No.1](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/986)
- PipeWire deadlock [No.2](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/982)
- [PipeWire returns empty buffers when it shouldn't](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/985)
- [Missing context](https://github.com/flatpak/xdg-desktop-portal/issues/572) for position property of pipewire streams
- [Inconsistency](https://github.com/flatpak/xdg-desktop-portal-gtk/issues/342) (fortunately not really a bug) between xdg-desktop-portal-gtk and xdg-desktop-portal-kde

### Missing features
- [PipeWire streams have no name](https://github.com/flatpak/xdg-desktop-portal/issues/569)
- [Can not get position of PipeWire streams](https://github.com/flatpak/xdg-desktop-portal/issues/571) (this breaks touch input mapping)
- [Can not get cursor data from PipeWire](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/120) (breaks switching displaying cursor without rerequesting permission to capture the screen)

Fortunately I could workaround all PipeWire deadlocks and at least on GNOME Weylus can now capture the desktop and windows and so far it seems not too unstable.

Feel free to try the latest [builds](https://github.com/H-M-H/Weylus/actions/runs/695611713#artifacts).

Considering the current situation I will definitely mark Wayland screen capture experimental and make it opt in.

**Comment by l-o-l** [comment]
Hi,

I've tried installing weylus on a Pi 4 running manjaro sway. Everything works other than desktop capture. I can capture chromium tabs and weylus itself, but the desktop capture returns the following warning:

WARN weylus::capturable: Failed to get list of capturables via dbus/pipewire: Failed to obtain screen capture.

Chromium itself is able to capture the desktop, as I am able to share the screen from web apps such as Microsoft Teams. Before running I set:

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
/usr/lib/xdg-desktop-portal -r & /usr/lib/xdg-desktop-portal-wlr

This works for chromium, and idea what could be done to get it to work in weylus?

**Comment by H-M-H** [comment]
This means that Weylus only captures windows available via XWayland. Please check if https://gitlab.gnome.org/snippets/19 also fails.

Some more questions: How exactly does the process for window/desktop selection work with chromium, do you get some kind of popup window that lets you select what to capture and does that popup window also appear for Weylus?

**Comment by dron1885** [comment]
Hi, also getting `WARN Failed to get list of capturables via dbus/pipewire: Failed to obtain screen capture.`.  No native Wayland windows and only a black desktop in the Capture list.

> This means that Weylus only captures windows available via XWayland. Please check if https://gitlab.gnome.org/snippets/19 also fails.

Yes, this snippet works.

> Some more questions: How exactly does the process for window/desktop selection work with chromium, do you get some kind of popup window that lets you select what to capture and does that popup window also appear for Weylus?

Don't know how chromium does this, but firefox (for example https://mozilla.github.io/webrtc-landing/gum_test.html) and the python snippet both change the mouse cursor to a cross and I need to click on a desktop I want to share. Actually, Weylus also does this.

Also, input forwarding to desktop do work, (but there is no image).

**Comment by mattpepin** [comment]
In Gnome/Mutter, the whole desktop works fine (Entire screen option)! It's pretty cool! Now I wish you could use Mutter's headless stuff and create a virtual screen! :)

**Comment by H-M-H** [comment]
@dron1885 @l-o-l I got it working under sway now, please check if the latest build works for you as well: https://github.com/H-M-H/Weylus/actions/runs/1012629238#artifacts

@mattpepin do you know how Mutter's headless stuff works? Perhaps I could add some examples or even an accompanying script to Weylus.

**Comment by dron1885** [comment]
@H-M-H Can confirm that it's working. Thanks!

**Comment by H-M-H** [comment]
> Can confirm that it's working. Thanks!

Excellent, thanks for testing!

> From my quick testing, while Waylus was showing a second monitor all inputs were translated to the first one.

This is a known problem and sadly not easily fixed. For monitors xdg-desktop-portal provides positions but unfortunately those are [compositor dependent/the coordinate system is unspecified](https://github.com/flatpak/xdg-desktop-portal/issues/572) and there is no straightforward way to translate them into something useful. For windows the situation is even worse as there is no position given.

Unfortunately I do not see this being solved in the foreseeable future. In my opinion the whole screen recording/remote desktop situation around Wayland is most unfortunate. There have been discussions to add screen recording to Wayland [for years](https://gitlab.freedesktop.org/wayland/wayland/-/issues/32) with the result that the team behind Flatpak is now somehow responsible for this and there are [no plans to extend Wayland itself or provide an official API/Protocol](https://gitlab.freedesktop.org/wayland/wayland/-/issues/150). This means the Flatpak devs effectively have full responsibility/control over how screen casting works. The problem now is that Flatpaks focus is not exactly to provide a nice screen cast/remote desktop interface for Wayland [1]. I can not and will not blame them for that, it is totally understandable if they deem some features required to get a nice remote desktop experience working unnecessary for Flatpak.
This is why I don't quite believe in this working anytime soon and the whole discussion doesn't even touch pipewire, which is still under heavy development.

If despite this anyone knows how to obtain the positions of pipewire streams in a way useful to Weylus I very much would like to hear that though.

[1]: There actually is a [remote desktop interface](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.RemoteDesktop). But among other things it doesn't handle [resizing windows](https://github.com/flatpak/xdg-desktop-portal/issues/571) or pressure sensitivity of touch input.

**Comment by raffaem** [comment]
Hello,

just a clarification. What does it mean that for Wayland there is no support for "capturing the cursor"?

If I move the stylus on my tablet, will the cursor move accordingly?

**Comment by H-M-H** [comment]
There are two problems related to this question:
- If you want to see the cursor in the video on your tablet you will need to refresh the capturable list as Wayland/pipewire does not support dynamically toggling its visibility once the video stream has been started. But be warned, the last time I tried this it ended up crashing my KDE desktop.
- Input mapping does not work. This means your cursor will move, but if you have more than one monitor connected or if you only mirror a window the position of the cursor will most likely be wrong.

**Comment by tinywrkb** [comment]
Wayland capture doesn't work for me. The only time it sort of worked is when I created a virtual display, and selected it, but the video was frozen, so that wasn't usable.  
In Sway, you can create a virtual display like this: `$ swaymsg create_output && swaymsg output "HEADLESS-1" resolution 2048x1536`, or alternatively via the config file.

**Comment by H-M-H** [comment]
Hmm, does this snippet: https://gitlab.gnome.org/snippets/19 work for you? Or alternatively does WebRTC screen sharing work? If one of these does work, this is most likely a problem with Weylus otherwise it's a problem with your setup.

**Comment by tinywrkb** [comment]
The snippet works as far as I can tell.  
OBS screen capture via PipeWire works for me perfectly, and also [WebRTC screen sharing](https://www.webrtc-experiment.com/screen-sharing/) in Chromium with the Wayland Ozone backend.

**Comment by H-M-H** [comment]
I just logged into a Sway session myself and after running
```console
$ export XDG_CURRENT_DESKTOP=sway
$ /usr/lib/xdg-desktop-portal -r
$ /usr/lib/xdg-desktop-portal-wlr -r
```
Weylus displays the whole desktop without problems. Please show me the output of `WEYLUS_LOG_LEVEL="DEBUG" weylus`, perhaps the log contains some clues.

**Comment by tinywrkb** [comment]
> I just logged into a Sway session myself and after running
> 
> ```
> $ export XDG_CURRENT_DESKTOP=sway
> $ /usr/lib/xdg-desktop-portal -r
> $ /usr/lib/xdg-desktop-portal-wlr -r
> ```

This is not needed if you override the systemd user service `xdg-desktop-portal.service` and set the value of  `XDG_CURRENT_DESKTOP` as `sway`.

```
# ~.config/systemd/user/xdg-desktop-portal.service.d/override.conf
[Service]
Environment="XDG_CURRENT_DESKTOP=sway"
```

> Weylus displays the whole desktop without problems. Please show me the output of `WEYLUS_LOG_LEVEL="DEBUG" weylus`, perhaps the log contains some clues.

I'm not sure how much this is helpful, but [here's the log](https://gist.github.com/tinywrkb/e17db83273b85a76ed1ea1c8699d3bd2).  
I also added the session bus capture, which can be viewed with Bustle and probably also Wireshark.
[weylus_2021-11-02T02:08:08.pcap.tar.gz](https://github.com/H-M-H/Weylus/files/7456886/weylus_2021-11-02T02.08.08.pcap.tar.gz)

**Comment by noneucat** [comment]
Weylus doesn't seem to work at all for me on Wayland, failing with this error message when I select the PipeWire output:
```
  WARN weylus::websocket: Failed to init screen cast: Failed to create element from factory name!
```
.. which looks like it's from `gstreamer-rs`, so I'm not entirely sure how to debug this. I verified that screen capture using `xdg-desktop-portal-wlr` works on my system using OBS. 
The name of the PipeWire output is titled `Pipewire Unknow, path: XXX` in the dropdown menu on the webapp, if that's of any help.

**Comment by noneucat** [comment]
Seems like it's happening here in `pipewire.rs`:
 
```
let src = gst::ElementFactory::make("pipewiresrc", None)?;
```

**Comment by noneucat** [comment]
Ah, looks like my distribution did not include the PipeWire GStreamer plugins correctly :) My bad!

**Comment by mgonzalezm** [comment]
Hello, 

I'm using sway/wayland (Xwayland disabled) on Archlinux, 
I followed the installation instructions stated in the Readme, but i can't make it work

when starting weylus from a alacritty terminal I get 
`WARN weylus::config: Failed to read configuration file: No such file or directory (os error 2)`
`Can't open display: wayland-1`

When run with `--no-gui` parameter I can connect, but it seems that weylus is still looking for X
`thread '<unnamed>' panicked at 'Can't open X display. Is it currently running?', /usr/local/cargo/git/checkouts/autopilot-rs-fed2c023a9e5d94a/63eed09/src/internal.rs:63:9`
`note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src/websocket.rs:415:60`

using `--wayland-support` makes no difference

is Xwayland compatibility necessary?

**Comment by H-M-H** [comment]
@mgonzalezm Hmm, you are right. Currently Xwayland is required. The culprit for the crash is the autopilot library which I currently use as fallback if uinput or my platform dependent screen capturing code does not work. autopilot assumes an X-server is present and just hard crashes if it isn't. Please try this build here https://github.com/H-M-H/Weylus/actions/runs/1831407176#artifacts and check if it crashes as well.

**Comment by mgonzalezm** [comment]
> Please try this build here

@H-M-H 
The crash is gone, but now I get: `ERROR weylus::websocket: Got invalid id for capturable: 0`.

I think something is missing in my setup, but i don't know what.
Why i keep getting `Can't open display: wayland-1` when running whithout --no-gui?  doesn't  wayland-1 is the default socket under wayland?

**Comment by H-M-H** [comment]
@mgonzalezm alright, so autopilot was indeed the cause for the crash. Have you made sure `xdg-desktop-portal-wlr` is up an running? You can verify whether it is running by checking if screen capturing works with OBS or Firefox.

The error message you got means that Weylus could not find any screens or windows to capture. Have you made sure to start Weylus with `--wayland-support`?

Regarding `Can't open display: wayland-1`, it looks like `fltk` only supports X/XWayland. I guess I'd have to rewrite the gui with another library (this wouldn't be that bad as the gui is rather minimal anyways, the actual problem is finding a nice gui library).

**Comment by H-M-H** [comment]
Hmm, this error stems from within gstreamer somewhere in this call to set_state: https://github.com/H-M-H/Weylus/blob/33cf5f138b5a7eefa8cf07c71eb0403a4fce849f/src/capturable/pipewire.rs#L148
Please check if this snippet works: https://gitlab.gnome.org/-/snippets/19 or alternatively check if OBS can capture your screen. This might be a problem unrelated to Weylus.

**Comment by mgonzalezm** [comment]
@H-M-H Yes OBS works ok, I can see my screen.

I wouldn't now if the snippet works, after the pop-up to select the monitor to share, this is all I can see in the terminal

`$ python xdp-screen-cast.py`
`session /org/freedesktop/portal/desktop/session/1_780/u1 created`
`sources selected`
`streams:`
`stream 36`

**Comment by rgrunbla** [comment]
Hello. I'm using weylus

**Comment by rgrunbla** [comment]
Hello,

I'm facing the same problem as @noneucat, i.e. I get a ```2022-05-04T16:29:01.243927Z  WARN weylus::websocket: Failed to init screen cast: Failed to create element from factory name!``` and screen sharing does not seem to work on my OS.

I'm using NixOS, and I tried running weylus with for example `GST_PLUGIN_PATH=/nix/store/v8yddpay5ilm3m59yj64pdnc13gjkav1-pipewire-0.3.49-lib/lib/gstreamer-1.0/libgstpipewire.so weylus` without much success (the module seems loaded according to strace, but I still get this message).

Any idea what could cause this / how to debug ?

Thanks.

**Comment by rgrunbla** [comment]
Running weylus with GST_DEBUG=5:

[log.txt](https://github.com/H-M-H/Weylus/files/8639133/log.txt)

**Comment by H-M-H** [comment]
@rgrunbla: Thanks for looking into this! `GST_PLUGIN_PATH` should point to the directory with the plugin, not the shared library itself. What is the output of `gst-inspect-1.0 pipewiresrc`?

Also, if this problem persists, please open a separate issue.

**Comment by Dmarc** [comment]
Maybe [this solution](https://www.tomshardware.com/how-to/use-tablet-or-phone-second-monitor-linux) using vdl and deskreen could be inspiring for Wayland support ?

**Comment by Iey4iej3** [comment]
It seems to me that, under Wayland (I am using `sway`), one cannot select a specific window, but "Pipewire unknown", which shows the current desktop. I am not sure whether it is possible to capture a specific window under Wayland, however.

**Comment by tutacat** [comment]
> It seems to me that under Wayland one cannot select a specific window, but "Pipewire unknown", which shows the current desktop. I am not sure whether it is possible to capture a specific window under Wayland, however.

No, it can't. For security, you select the window only in the pipewire popup. The program can't access every window instantly, and without confirmation. Weylus isn't forwarding the window title, but that's not a problem. To change the window, you can use the 'refresh sources' button, or reload the page, then choose the window you want to mirror on your screen.

For most people, it may be easier to just mirror the whole display. With X11 there are normally no controls to what programs can access on the same server. Giving access to the monitor through Pipewire doesn't give access to all windows.

You *may* still be able to access X11 windows directly through Weylus, but you won't be able to access Wayland windows.

**Comment by Iey4iej3** [comment]
> To change the window, you can use the 'refresh sources' button, or reload the page, then choose the window you want to mirror on your screen.

I am not sure whether I misconfigured something. I compiled the latest Weylus without compiling `ffmpeg` (I failed to compile `ffmpeg` for some reasons). I am under `sway`.

I have exactly tried this: after clicking "refresh", the mouse icon becomes a cross, which seems to indicate me to select a windows, and after selection, the title of selected window does not appear in the drop list.

**Comment by tutacat** [comment]
Weylus doesn't forward the window title to the client. Just select Pipewire, which is usually selected by default. You will probably only be able to access the window you selected.

25 Aug 2023 11:27:48 Iey4iej3 ***@***.***>:

**Comment by Iey4iej3** [comment]
No, it is accessing the current display (although the cross icon seems to indicate that I was supposed to select a specific window).

**Comment by tutacat** [comment]
Are you selecting Pipewire or X11 display? The default cursor on X11 is an X. You only choose the window on the actual computer, it should show up on the monitor, once you load the webpage.

25 Aug 2023 11:50:17 Iey4iej3 ***@***.***>:

**Comment by Iey4iej3** [comment]
> Are you selecting Pipewire or X11 display? The default cursor on X11 is an X. You only choose the window on the actual computer, it should show up on the monitor, once you load the webpage. 25 Aug 2023 11:50:17 Iey4iej3 ***@***.***>:

I believe that it is Pipewire (the cursor, more precisely being "+" in place of "X", is very different from the default cursor of X): it is triggered by "refresh list" or truly refreshing the site, and without clicking anything, the window list is empty.

**Comment by tutacat** [comment]
Yes that is then. The pipewire selection depends on your window manager, so that will be how sway shows it.

25 Aug 2023 12:03:06 Iey4iej3 ***@***.***>:

**Comment by Iey4iej3** [comment]
After having searched, I see that it is an issue of `xdg-desktop-portal-wlr`: https://github.com/emersion/xdg-desktop-portal-wlr/issues/107

**Comment by matejdro** [comment]
To anyone getting `  WARN weylus::websocket: Failed to init screen cast: Failed to create element from factory name!`: It appears that latest release is very old and does not contain proper Wayland support yet. Building from `master` seems to fix the issue.

**Comment by MarkGhebrial** [comment]
For any Arch + PipeWire users getting the `Failed to init screen cast: Failed to create element from factory name!` error, installing the `gst-plugin-pipewire` package fixed it for me.

**Comment by H-M-H** [comment]
@dryBoneMarrow as far as I understand the Hyprland wiki about [screen sharing](https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/) it is supposed to work with `xdg-desktop-portal` and weylus should support that. This is the de-facto standard for screen sharing on Wayland, there is a list with supported DEs on the arch wiki: https://wiki.archlinux.org/title/XDG_Desktop_Portal#List_of_backends_and_interfaces

**Comment by W1nKille3r** [comment]
On KDE Neon 6.2, weylus just refuses to work: Failed to init screen cast!

**Comment by vafu** [comment]
Same for me on hyprland: Failed to init screen cast!
Screen sharing works in general (browser, OBS etc)
touch input is working fine. 

I want to help the project, is there any lead as to what might be going on?

**Comment by wisegod62** [comment]
Any updates? I would love to help but I know absolutely nothing about X11 and Wayland. Any updates?
