### ISSUE TITLE
VAAPI aaceleration crashes

### ISSUE THREAD

**Issue by raffaem** [H-M-H/Weylus#72]
When I try to activate VAAPI acceleration:

```
Mar 21 17:57:00.088  INFO weylus::web: Client connected: 127.0.0.1:32835
Mar 21 17:57:00.201  INFO weylus::websocket: WS-Client authenticated: 127.0.0.1:45643!
Output #0, mp4, to '(null)':
    Stream #0:0: Video: h264 (High), vaapi_vld, 1920x1080, q=2-31
Mar 21 17:57:00.257  INFO weylus::log: Video: 1920x1080@h264_vaapi pix_fmt: bgr0
[AVHWFramesContext @ 0x7f6a9005b0c0] Failed to write image to surface 0x13: -1 (unknown libva error).
[AVHWFramesContext @ 0x7f6a9005b0c0] Failed to write image to surface 0x13: -1 (unknown libva error).
[AVHWFramesContext @ 0x7f6a9005b0c0] Failed to write image to surface 0x13: -1 (unknown libva error).
[AVHWFramesContext @ 0x7f6a9005b0c0] Failed to write image to surface 0x13: -1 (unknown libva error).
Segmentation fault (core dumped)
```

NVENC works fine.

**Comment by H-M-H** [comment]
This may be related to https://github.com/H-M-H/Weylus/issues/62#issuecomment-780251858, please run Weylus with `WEYLUS_LOGLEVEL=TRACE ./weylus` and upload the output here. You can also try debugging it with gdb: `gdb ./weylus` --> `run` --> `bt` --> paste output here.

**Comment by raffaem** [comment]
Not much but I suspect he is trying to use the Intel CPU instead of the NVIDIA GPU
```
$ ./start_weylus.sh 
Mar 21 19:56:42.027  INFO weylus::web: Webserver listening at 0.0.0.0:1701...
Mar 21 19:56:45.976  INFO weylus::web: Web-Client authenticated: 127.0.0.1:50271.
Mar 21 19:56:45.976  INFO weylus::web: Client connected: 127.0.0.1:50271
Mar 21 19:56:46.076  INFO weylus::websocket: WS-Client authenticated: 127.0.0.1:45453!
Output #0, mp4, to '(null)':
    Stream #0:0: Video: h264 (High), vaapi_vld, 1920x1080, q=2-31
Mar 21 19:56:46.170  INFO weylus::log: Video: 1920x1080@h264_vaapi pix_fmt: bgr0
[AVHWFramesContext @ 0x7f23c405b0c0] Failed to write image to surface 0x13: -1 (unknown libva error).
./start_weylus.sh: line 7: 24644 Segmentation fault      (core dumped) WEYLUS_LOGLEVEL=TRACE ./weylus
```

And with GDB
```
0$ gdb weylus
GNU gdb (Ubuntu 9.2-0ubuntu2) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from weylus...
(No debugging symbols found in weylus)
(gdb) run
Starting program: /media/raffaele/intdata/data/linux/software/appimage/weylus_0.10/weylus 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6878640 (LWP 24769)]
[New Thread 0x7ffff6677640 (LWP 24770)]
[New Thread 0x7ffff6473640 (LWP 24771)]
[New Thread 0x7ffff626c640 (LWP 24773)]
[New Thread 0x7ffff6068640 (LWP 24774)]
[New Thread 0x7ffff5e64640 (LWP 24775)]
[New Thread 0x7ffff5c60640 (LWP 24776)]
[New Thread 0x7ffff5a5f640 (LWP 24777)]
[New Thread 0x7ffff585b640 (LWP 24778)]
[New Thread 0x7ffff5657640 (LWP 24779)]
[New Thread 0x7ffff5450640 (LWP 24780)]
[New Thread 0x7ffff524c640 (LWP 24781)]
[New Thread 0x7ffff504b640 (LWP 24782)]
[New Thread 0x7ffff4e44640 (LWP 24783)]
[New Thread 0x7ffff4c43640 (LWP 24784)]
[New Thread 0x7ffff4a3f640 (LWP 24785)]
[New Thread 0x7ffff4838640 (LWP 24786)]
[New Thread 0x7ffff4634640 (LWP 24787)]
Mar 21 19:57:50.279  INFO weylus::web: Webserver listening at 0.0.0.0:1701...
Mar 21 19:57:53.329  INFO weylus::web: Web-Client authenticated: 127.0.0.1:44375.
Mar 21 19:57:53.329  INFO weylus::web: Client connected: 127.0.0.1:44375
[New Thread 0x7ffff43f7640 (LWP 24788)]
[New Thread 0x7fffa7fff640 (LWP 24789)]
Mar 21 19:57:53.434  INFO weylus::websocket: WS-Client authenticated: 127.0.0.1:53941!
Output #0, mp4, to '(null)':
    Stream #0:0: Video: h264 (High), vaapi_vld, 1920x1080, q=2-31
Mar 21 19:57:53.556  INFO weylus::log: Video: 1920x1080@h264_vaapi pix_fmt: bgr0
[AVHWFramesContext @ 0x7fffa005b0c0] Failed to write image to surface 0x13: -1 (unknown libva error).

Thread 21 "weylus" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa7fff640 (LWP 24789)]
0x00007fffa70a0bc5 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
(gdb) bt
#0  0x00007fffa70a0bc5 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
#1  0x00007fffa7091bf4 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
#2  0x00007fffa707861a in ?? () from /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
#3  0x00007fffa72865e3 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
#4  0x00007fffa728a016 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
#5  0x00007fffa728a29a in ?? () from /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
#6  0x00007fffa7257f92 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
#7  0x00007ffff7df92b0 in vaPutImage () from /lib/x86_64-linux-gnu/libva.so.2
#8  0x00005555563e443e in ?? ()
#9  0x00005555563df88f in ?? ()
#10 0x00005555563d3dcf in ?? ()
#11 0x00005555563dcc64 in ?? ()
#12 0x00005555563dcde9 in ?? ()
#13 0x00005555563e475e in ?? ()
#14 0x00005555563dfe97 in ?? ()
#15 0x0000555555962640 in fill_bgra ()
#16 0x00005555559069cd in ?? ()
#17 0x0000555555894841 in ?? ()
#18 0x0000555555904c07 in ?? ()
#19 0x000055555583258a in ?? ()
#20 0x00007ffff7bb2590 in start_thread (arg=0x7fffa7fff640) at pthread_create.c:463
#21 0x00007ffff76dd223 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) quit
A debugging session is active.

	Inferior 1 [process 24765] will be killed.

Quit anyway? (y or n) y
```

**Comment by H-M-H** [comment]
Yes, iHD is an intel driver, try setting LIBVA_DRIVER_NAME to i965 for example, in my experiments that driver worked better. Alternatively check the readme on how to find other valid drivers you can select with LIBVA_DRIVER_NAME.

**Comment by raffaem** [comment]
Fixed.

Thank you very much!
